name: Daily Push

permissions:
  contents: write

on:
  schedule:
    # 台灣 5:00 AM ～ 4:00 PM，每 30 分鐘
    # 對應 UTC : 21:00 - 08:00
    #---------------------------------------------
    # 跨子夜處理 : 21點, 22-23點, 0點, 1-7點
    - cron: '7,37 21 * * *'
    - cron: '7,37 22-23 * * *'
    - cron: '7,37 0 * * *'
    - cron: '7,37 1-7 * * *'
    - cron: '7 8 * * *'

    # 台灣 7:30 PM ～ 1:00 AM，每 15 分鐘
    # 對應 UTC : 11:30 - 17:00
    #------------------------------------------------------------------
    # 處理邏輯 : 11點半後半, 12-16點整點/15/30
    - cron: '37,52 11 * * *'
    - cron: '7,22,37,52 12-16 * * *'
    - cron: '7 17 * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python run_daily_new_16.py
